<h1>Detailansicht Raum</h1>
<?php
$form = $this->form;
$form->prepare();
?>
<?php echo $this->form()->openTag($form) ?>
    <dl class="zend_form">
        <?php // TODO // echo $this->formElementErrors($form->get('name')) ?>
        <dt><?php echo $this->formLabel($form->get('name')) ?></dt>
        <dd><?php echo $this->formInput($form->get('name')) ?></dd>
        <dt><?php echo $this->formLabel($form->get('humidity')) ?></dt>
        <dd><?php echo $this->formInput($form->get('humidity')) ?></dd>
        <dt><?php echo $this->formLabel($form->get('temperature')) ?></dt>
        <dd><?php echo $this->formInput($form->get('temperature')) ?></dd>
        <dt><?php echo $this->formLabel($form->get('switch')) ?></dt>
        <dd><?php echo $this->formRadio($form->get('switch')) ?></dd>
        <dt><?php echo $this->formLabel($form->get('motion')) ?></dt>
        <dd><?php echo $this->formRadio($form->get('motion')) ?></dd>
        <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php endif ?>
        <dd><?php echo $this->formInput($form->get('submit')) ?></dd>
    </dl>
<?php echo $this->form()->closeTag() ?>
