<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('EHC Web App'); ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php 
        	echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery.jqplot.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
	
        <!-- Scripts -->
        <?php 
        	echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/script.js')
                                      ->prependFile($this->basePath() . '/js/showHide.js')
                                      ->prependFile($this->basePath() . '/js/excanvas.js')
                                      ->prependFile($this->basePath() . '/js/RGraph.bar.js')
                                      ->prependFile($this->basePath() . '/js/RGraph.line.js')
                                      ->prependFile($this->basePath() . '/js/RGraph.common.core.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js')
        ?>	
    </head>
    <body>
    	<!-- Navigation -->
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <!--  
                    <a class="brand" href="
                    <?php 
                    	// echo $this->url('home') 
                    ?>">EHC</a>
                    -->
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                            <li><a href="<?php echo $this->url('ehometest') ?>" title="Test E|Home Center">Test</a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <!-- Hauptcontainer -->
        <div class="container">
        	<?php // FlashMessenger
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><ul><li>')
    		->setMessageSeparatorString('</li><li>')
     		->setMessageCloseString('</li></ul></div>');
echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>
            <?php echo $this->content; ?>
            <hr>
            <footer>
            	<!-- E|Home-Center -->
            	<p><a href="http://www.ehome-center.de" title="E|Home-Center">E|Home-Center-Zentraleinheit</a> powered by Zend Framework</p>
            	<!-- 
                <p>&copy; 2005 - <?php // echo date('Y') ?> by Zend Technologies Ltd. <?php // echo $this->translate('All rights reserved.') ?></p>
                 -->
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
        <?php 
        if (!$this->localNetwork){
			echo '<!-- Counter -->';
			echo '<script type="text/javascript" src="http://fc.webmasterpro.de/counter.php?name=jochen1980_ehcwebapp"></script>';
			echo '<noscript><div><img src="http://fc.webmasterpro.de/as_noscript.php?name=jochen1980_ehcwebapp" style="width:1px;height:1px;" alt="" /></div></noscript>';
		}
        ?>
    </body>
</html>
